mkdir -p ./Thesis/code/r_code
mkdir -p ./Thesis/code/r_code/chapter_3_simulations
mkdir -p ./Thesis/code/r_code/helper_functions
mkdir -p ./Thesis/code/r_code/results_application
mkdir -p ./Thesis/code/r_code/results_application/multivariate_models
mkdir -p ./Thesis/code/r_code/results_application/multivariate_models/prepared_data
mkdir -p ./Thesis/code/r_code/results_application/univariate_models
mkdir -p ./Thesis/code/r_code/application
mkdir -p ./Thesis/code/r_code/chapter_2_simulations
mkdir -p ./Thesis/code/r_code/chapter_2_simulations/bias_variance_decomposition
mkdir -p ./Thesis/code/r_code/results_simulation
mkdir -p ./Thesis/code/r_code/results_simulation/results_overfitting_behaviour
mkdir -p ./Thesis/code/r_code/results_simulation/results_multivariate_timeseries
mkdir -p ./Thesis/code/r_code/results_simulation/results_multivariate_timeseries/distribution_misspecified
mkdir -p ./Thesis/code/r_code/results_simulation/results_multivariate_timeseries/saved_models
mkdir -p ./Thesis/code/r_code/results_simulation/results_multivariate_timeseries/saved_models/models_nonlinear_mgarch
mkdir -p ./Thesis/code/r_code/results_simulation/results_multivariate_timeseries/saved_models/models_multivariate_timeseries
mkdir -p ./Thesis/code/r_code/results_simulation/results_multivariate_timeseries/form_misspecified
mkdir -p ./Thesis/code/r_code/results_simulation/results_multivariate_timeseries/form_misspecified/saved_models
mkdir -p ./Thesis/code/r_code/results_simulation/results_semiparametric_model
mkdir -p ./Thesis/code/r_code/results_simulation/results_semiparametric_model/results_numeric
mkdir -p ./Thesis/code/r_code/results_simulation/results_semiparametric_model/visualisation_approximation
mkdir -p ./Thesis/code/r_code/results_simulation/results_semiparametric_model/plotting_epochs
mkdir -p ./Thesis/code/r_code/results_simulation/results_high_dimensional
mkdir -p ./Thesis/code/r_code/results_simulation/results_bias_variance
mkdir -p ./Thesis/code/r_code/results_simulation/results_bias_variance/results_multilayer
mkdir -p ./Thesis/code/r_code/results_simulation/results_bias_variance/comparison_overfitting
mkdir -p ./Thesis/code/r_code/results_simulation/results_bias_variance/results_singlelayer
mkdir -p ./Thesis/code/r_code/results_simulation/results_stochastic_timeseries
mkdir -p ./Thesis/code/r_code/results_simulation/results_stochastic_timeseries/results_numeric